quarkus.http.port=${PORT:8080}
quarkus.http.host=0.0.0.0
quarkus.application.name=emdashpolice
quarkus.http.cors.enabled=${QUARKUS_HTTP_CORS_ENABLED:false}
quarkus.http.cors.origins=${QUARKUS_HTTP_CORS_ORIGINS:}
